name: API Build and Deploy Production

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api-prod.yaml"

concurrency: 
  group: api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONFIG_JSON: ${{ secrets.API_PROD_CONFIG }}
      APP_YAML: ${{ secrets.API_PROD_GCP_APP_YAML }}
      DISPATCH_YAML: ${{ secrets.COMMON_GCP_DISPATCH_YAML }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: npm 7
        run: npm install -g npm@7
      - name: API and GCP Config
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            fs.writeFileSync('./api/src/data/config.prod.json', process.env.CONFIG_JSON)
            fs.writeFileSync('./dispatch.yaml', process.env.DISPATCH_YAML)
            fs.writeFileSync('./app.yaml', process.env.APP_YAML)
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: latest
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy
        run: |
          cd api
          gcloud app deploy app.yaml dispatch.yaml --quiet
