name: Format & Lint Check

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    install_deps:
        strategy:
          matrix:
            project: [api, client]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install Dependencies
              run: cd ${{ matrix.project }} && npm install
            - name: Format Check
              run: npm run format:check
            - name: Lint Check
              run: npm run lint
